function RendererPhotoshopConfig()
{
  this.FRAGMENT_LAYERNAME_PREFIX = 'fragment:';
  this.DEFAULT_CANVASOFFSET = 0;
  this.DEFAULT_CANVASOFFSETX = 0;
  this.DEFAULT_CANVASOFFSETY = 0;
  this.DEFAULT_RESOLUTION = 30;
  this.DEFAULT_DOCUMENTMODE = NewDocumentMode.RGB;
  this.DEFAULT_DOCUMENTFILL = DocumentFill.WHITE;
  this.DEFAULT_BITDEPTH = BitsPerChannelType.SIXTEEN;
  this.DEFAULT_COLORPROFILETYPE = ColorProfile.WORKING;
  this.DEFAULT_GRIDSIZE = 0;
  this.DEFAULT_GRIDSIZEX = 0;
  this.DEFAULT_GRIDSIZY = 0;
  this.DEFAULT_GRIDGUTTER = 0;
  this.DEFAULT_GRIDGUTTERX = 0;
  this.DEFAULT_GRIDGUTTERY = 0;
  this.DEFAULT_GRIDDIRECTION_HORIZONTAL = 'horizontal';
  this.DEFAULT_GRIDDIRECTION_VERTICAL = 'vertical';
  this.DEFAULT_GRIDDIRECTION = this.DEFAULT_GRIDDIRECTION_HORIZONTAL;
  this.DEFAULT_APPLYREMAINDER = new Boolean(true);
  this.DEFAULT_RANDOMCOORDINATE = new Boolean(true);
  
  /* Photoshop Javascript References CS6.pdf, page 214 */
  this.VALID_APPLICATIONUNITS  = [Units.CM,Units.MM];
  this.DEFAULT_APPLICATIONUNITS = Units.CM;
  this.DEFAULT_APPLICATIONUNITSTRING = 'cm';
  this.DEFAULT_UNITS = this.DEFAULT_APPLICATIONUNITS;
  this.DEFAULT_UNITSTRING = this.DEFAULT_APPLICATIONUNITSTRING;
  this.VALID_DEBUGLEVEL = [0,1,2];
  this.DEFAULT_DEBUGLEVEL = 2;
  this.DEFAULT_ENABLENOTIFIER = Boolean(true);
};
